disabled_rules:
- trailing_whitespace
- file_length
- identifier_name
- large_tuple
- function_parameter_count
- shorthand_operator

### Remove
- type_body_length
- function_body_length
- cyclomatic_complexity

included:

excluded:
- Pods

line_length: 200
